### ISSUE TITLE
codegen issues

### ISSUE THREAD

**Issue by wasaga** [pomerium/enterprise-client-python#12]
# Issues
1. package and tools versions are not pinned. 
2. uses protocV4, while console is on v3.20.3.
3. codegen missing for envoy, xds and udpa packages.
4. code carryover from https://github.com/pomerium/enterprise-client without ability to test before commit - causes broken commits to `main` - https://github.com/pomerium/enterprise-client-python/actions/runs/3019748836/jobs/4855978582

# Solution
1. perform python codegen in this repo 
2. pin package and tool versions
3. get rid of https://github.com/pomerium/enterprise-client

**Comment by calebdoxsey** [comment]
I am stuck on

```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

```

I spent many hours on this. The generated code is impossible to get working out of the box. We have to edit the files using `sed` and a lot of other very clunky, brittle hacks that are guaranteed to fail every time we do a release.

I will try again tomorrow.
